### ISSUE TITLE
Add option for download location

### ISSUE THREAD

**Issue by chesh111re** [transilluminate/download-station#1]
Hi!
Do you plan to add a create method with file location (on the pc or on nas)

I tried to implement this in c#, but never got any results.

There is similar logic in this repository, but I'm not that good at power shell scripts: https://github.com/xaozai/ds-cli

**Comment by transilluminate** [comment]
I've updated the script to support this.

Note: it does not check to see if it's a valid download folder, or create it if it does not exist. That is outside of the API. If it's not a valid destination, it will give an error (403).

The best way to understand what it needs to be supplied is to:
- go to your download station web page
- look at a currently running download
- look under 'General' at the 'Destination' info
- copy that format to supply to the script!

**Comment by chesh111re** [comment]
Thank you for answer!
Can you show example string to create task with torrent file?

**Comment by transilluminate** [comment]
```
adrian@DiskStation:~$ mkdir /volume1/DiskStation/Downloads/Linux

adrian@DiskStation:~$ ./bin/download-station.sh add "https://releases.ubuntu.com/22.10/ubuntu-22.10-desktop-amd64.iso.torrent" DiskStation/Downloads/Linux
Initialising environment... OK!
Checking API on Synology... OK!
=> Auth_URL: /webapi/entry.cgi
=> DS_URL:   /webapi/DownloadStation/task.cgi
Getting authentication token... OK!
=> SID: x3nF6Ef7oWdRgYSREGcNPZ4C9gXSFegb8QMiLDraim4uZrl53fZP0Ys-s2Ukl3hIaE03BZcrwHw_qwCWejOTBQ
Adding URL... OK!
Cleaning up... OK!

adrian@DiskStation:~$ ./bin/download-station.sh list
Initialising environment... OK!
Checking API on Synology... OK!
=> Auth_URL: /webapi/entry.cgi
=> DS_URL:   /webapi/DownloadStation/task.cgi
Getting authentication token... OK!
=> SID: wchMJBohboQWnTflpJhUgZRtjLY0pfQm0GqHPVHxsrEpMEYSAGbhP7dcwa1lnRqxDM7SVO0qI3Sce8UcvH7xfs
Getting download tasks... OK!
=> Number of downloads: 1
=> Format: id,"title",status,download speed,downloaded,size,percentage complete
=> dbid_376,"ubuntu-22.10-desktop-amd64.iso",downloading,0B/s,0B,3.8GB,0.0%
Cleaning up... OK!
```

**Comment by transilluminate** [comment]
So I created Linux folder under the DiskStation share Downloads folder.

Then added the torrent file:
`download-station.sh add "https://releases.ubuntu.com/22.10/ubuntu-22.10-desktop-amd64.iso.torrent" DiskStation/Downloads/Linux`

You’ll need to check your paths etc. 

This is why I didn’t want to implement it - just use the default downloads folder and move it afterwards. If adding on iOS, I’ve included a sample shortcut which works over SSH

**Comment by chesh111re** [comment]
Thank you! Perfect answer

But, some torrent files do not have a link like https://...

So I wondered what to do if I have a downloaded file on my device (pc or phone) or if the file is already on NAS

**Comment by transilluminate** [comment]
The API does not support this - only links which are accessible via the internet.

You’d need to upload it to the NAS another way (scp or smb for example), and possibly drop it into a watch folder.

**Comment by chesh111re** [comment]
It's so sad(
But if create task from UI (choose file from pc) i can intercept request and see another API (download station 2)

I'm just talking for information

For example: https://www.reddit.com/r/synology/comments/110mobb/what_is_current_api_version_for_downloadstation/

I have asked support, but they are silent

**Comment by transilluminate** [comment]
Edit: you are right re: can send file across [Syno DS API](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/DownloadStation/All/enu/Synology_Download_Station_Web_API.pdf) However, it's outside my use-case and scope of this simple script. Happy for you to fork the script and add support... :)

A solution that would be easier would be to use secure copy a .torrent into the [watched folder](https://kb.synology.com/en-global/DSM/help/DownloadStation/download_setup?version=7)
`scp -O your.torrent user@synology.local:/path/to/watched/folder`
